# AWS QuickStart OpenShift Installation
#
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=openshift-enterprise
containerized=false
openshift_master_cluster_method=native
openshift_router_selector='region=infra'
openshift_registry_selector='region=infra'
#openshift_master_api_port=8443
#openshift_hosted_manage_registry=false
#openshift_hosted_manage_router=false
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
